### ISSUE TITLE
DEMO: Targeted GC-MS Full Scan

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/SmartPeak2#112]
### Description
Igor from the CHO group would like to set up an automated pipeline for Targeted GC-MS full scan data processing for fluxomics applications.  

### Objectives
- [x] internally validate the workflow using a selection of their manually processed data
- [x] verify the accuracy of the resulting data with the users
- [ ] train the users on the current command line version of the software

### Validation
- Mutually agreed upon by us and the CHO informatics group
