### ISSUE TITLE
Command Line App Main Menu Refactor

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/SmartPeak2#126]
### Description
This epic contains both Issues discovered based on an internal review of the CLI application, as well as discovered features that will be needed for usability.

### Objectives
- Move the main menu of the CLI to mirror the data flow and logic of what will be the eventual GUI (see mock below)
- Implement several needed main menu items to ease usability
- Implement using a "Tree of Views" pattern

### Need to have fixes/features (In order of importance)
- [x] 1. Issue #122 main menu item load file
- [x] 2. Issue #124 transition/transition group QC message
- [x] 3. Issue #120 file integrity check
- [ ] 4. Issue #123 CLI installation packaging
~5. Issue #117 tooltip~ *This has been moved to "Listener-Caller" epic*
- [x] 6. Issue #118 main menu item quick info
- [x] 7. Issue #119 main menu item report

### Nice to have fixes/features
- [x] 1. Issue #125 dynamic pathname confirmation
- [ ] 2. Issue #TBD Help menu with version and documentation information

### Main menu mock
![SmartPeak_UI-02.png](https://images.zenhubusercontent.com/5a1748468a75884b90889d72/d05274ac-8a44-4275-95e1-8b51feb78ed8)

Note that the "report" in "actions" should allow for reporting of the "featureSummary" and "sequenceSummary"
