### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/SmartPeak2#15]
### Description
As a user, I would like to have a Graphical user interface for SmartPeak that allows one to navigate the file system when importing files, view chromatograms and spectrum from data files, edit and modify settings and parameters, and view and edit data in an in-app table editor.  

### Workflow steps
1. Import raw data and data upload validation
2. Workflow/algorithm parameterization
3. Workflow/algorithm execution, monitoring, and error reporting
4. Data review
5. Data reporting

### Objectives
- [ ] File IO routines
- [ ] new session wizard
- [ ] algorithm parameters, filters, and settings tabular editors
- [ ] tabular data editor and viewer
- [ ] graphical window for peak plots, QC plots, and analysis plots
- [ ] sequence tag manager
- [ ] sequence progress bar manager
