### ISSUE TITLE
MRMFeatureValidator Upgrade

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/SmartPeak2#152]
### Description
We would like to integrate the MRMFeatureValidator as a new data processing workflow step.  This also implies that a workflow step for loading a reference data step will also be added.  In addition, several bug that were identified and changes that were found to be needed to use the MRMFeatureValidator in practice will need to be integrated.

### Objectives
- [x] Bug fixes and code cleanup of MRMFeatureValidator class
- [x] unit test coverage for MRMFeatureValidator class
- [x] create a `RawDataProcessor` class for running the MRMFeatureValidator
- [x] create a `RawDataProcessor` class for loading the reference data
- [x] unit test coverage for new `RawDataProcessor` classes
- [ ] CLI and GUI options for running the new workflow steps
- [ ] updates to import/export methods to allow for running the MRMFeatureValidator workflow

#### Bug fixes and integration changes
- [x] https://github.com/dmccloskey/SmartPeak2/compare/validation#diff-a83714c48455d1c46138484a672a1039R393
- [x] https://github.com/dmccloskey/SmartPeak2/compare/validation#diff-95c309a7276ad692a8010533a1fb80b1R38
- [x] https://github.com/dmccloskey/SmartPeak2/compare/validation#diff-95c309a7276ad692a8010533a1fb80b1R59
- [x] https://github.com/dmccloskey/SmartPeak2/compare/validation#diff-95c309a7276ad692a8010533a1fb80b1R68
- [x] https://github.com/dmccloskey/SmartPeak2/compare/validation#diff-4d14757bac7e9740af7d6a2da4f526e2R34
- [x] https://github.com/dmccloskey/SmartPeak2/compare/validation#diff-65e5927baad302f270ce1a475038a8b9R776

#### IO related changes
- [x] https://github.com/dmccloskey/SmartPeak2/compare/validation#diff-5e57c465788e75ff938864610f155460R372
- [x] https://github.com/dmccloskey/SmartPeak2/compare/validation#diff-a521007f9bc52093797a2f3ca9e91110R49

#### New options to add to the FeatureSummary and SequenceSummary export
- [x] https://github.com/dmccloskey/SmartPeak2/compare/validation#diff-686e54e508fe487b03dc429ec2797d83R56

#### Specific changes to the Filename class
- [x] https://github.com/dmccloskey/SmartPeak2/compare/validation#diff-cb84dc19308f71cf63ecb645b1266f7bR42
- [x] https://github.com/dmccloskey/SmartPeak2/compare/validation#diff-686e54e508fe487b03dc429ec2797d83R42

### Validation
- [x] Passing unit tests
- [ ] Working CLI and GUI
- [ ] Win/Linux build
