### ISSUE TITLE
Port of .py to .cpp

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/SmartPeak2#16]
### Description
Port of python implemented classes and workflows into C++ for seamless native integration and deployment

### Objectives
- [x] port existing .py classes to C++ (modules for io, core, tests, and examples)
- [x] port .py algorithms to C++ (waiting on Svetlana)

### Validation
- [x] working tests ported from .py
- [ ] working examples ported from .py
