### ISSUE TITLE
Metabolomics data QC module

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/SmartPeak2#171]
### Description
As a user, I would like to know what peaks have low "quality" scores so that I can manually check them to see if anything went wrong.  I would also like to set pre-determined thresholds for the acceptable variance of QC pooled samples.  And finally, I would like a single "quality" score for each of the metabolite levels that are reported to the end user.

### Objectives (Back end)
- [ ] Modify MRMFeatureQC to include a structure for setting the upper and lower bounds for metabolite concentrations and variances for QC samples
- [ ] Modify MRMFeatureFilter to include a method for calculating the variance of QC pooled samples and checking if the current sample is within the acceptable range
- [ ] Add a new RawDataProcessor method to call the new QC check method
- [ ] Create a new RawDataProcessor method that uses weighting factors of predetermined amounts to combine the transition score, transition group score, and QC scores into a single score that can be reported to end users

### Validation (Backend)
- Passing OpenMS CI (unit tests, builds, etc.)
- Passing SmartPeak CI (unit tests, builds, etc.)

### Objectives (Frontend)
- [ ] Dashboard with summary statistics and plots that provide an overview of the run quality including the number of features that are above/below a particular threshold
- [ ] An easy way to quickly view only those samples/features that did not pass the quality thresholds

### Validation (Frontend)
- Passing SmartPeak CI (unit tests, builds, etc.)
