### ISSUE TITLE
SequenceFile Converter and Reader

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/SmartPeak2#207]
### Description
As a user, I would like to be able to read in sequence files from various instruments instead of having to copy and paste into the current SmartPeak Sequence file format.

### Objectives
- [ ] Sequence file readers for ABSCIEX, Thermo, Bruker, Agilent, and Waters sequence file formats
- [ ] Sequence file converters for ABSCIEX, Thermo, Bruker, Agilent, and Waters sequence file formats
- [ ] Unit tests for reading the different sequence file formats
- [ ] Unit tests for parsing the different sequence file formats

### Validation
- [ ] Passing unit tests
- [ ] Working linux/win builds
