### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/SmartPeak2#3]
### Description
Formal record of all application events, messages, and warnings into a time-stamped document that can be used for debugging and audit trail purposes

### Objectives
- [ ] decide upon third party integration or creating a minimal version
- [ ] add external logging to external build
- [ ] add in application logging
~- [ ] add in features that comply with regulatory Audit Trail requirements~

### Requirements for the `Event` object
1. Realtime output to the stream (control of the verbosity level)
2. Realtime output to a text file (control of the text output level)
3. Record of events in a vector that can then be searched or pushed to a database
4. time stamps
5. class that generated the "event"
6. thread that generated the event

### Requirements for the `Logger` object
1. can log to file or output to screen at specified time intervals
2. has multiple logging levels and a way to specify which levels to log to

### References
- Reviews of C++11 header only loggers
  - https://softwarerecs.stackexchange.com/questions/31775/header-based-c-logging-library
  - https://stackoverflow.com/questions/5028302/small-logger-class
  - easylogging and spdlog appear the most promising for 3rd party incorporation
- Recommended C++11 header only loggers that fulfill the above requirements
  - easylogging: https://github.com/zuhd-org/easyloggingpp
  - spdlog: https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/logger.h
  - cpplog: https://github.com/andrew-d/cpplog
  - https://github.com/fjanisze/logger
  - Dr. Dobbs 2013: http://www.drdobbs.com/cpp/a-lightweight-logger-for-c/240147505?pgno=3
  - Dr. Dobbs 2017: http://www.drdobbs.com/cpp/logging-in-c/201804215 
- Observer pattern: https://thispointer.com/designing-a-configurable-logging-framework-using-observer-design-pattern/
