### ISSUE TITLE
User Session

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/SmartPeak2#8]
### Description
As a user, I would like to consolidate all .csv input and output files into a binary file format (session object) that can be loaded, saved, and queried.  The session object should be able to be shared by users across multiple computers (with potentially different OSs).  Note that the sesson object will not store the raw .mzML files, but instead will point to them using the `Filenames` class.  The user will need to update the path of the raw .mzML file if they e.g., copy and paste the session to a new directory or computer.  The session should allow for "undo" and "redo" functionality.

### Requirements
- Single binary file format
- Multi-thread transaction support
- transaction speed performance: TBD
- disk IO: TBD
- memory size limitations: TBD

### Objectives
- [ ] save application data to persistent storage (e.g., sqlite)
- [ ] convert OpenMS structures to/from table structures
- [ ] load and save sessions
- [ ] session audit tracking
- [ ] undo and redo session commands
