### ISSUE TITLE
Re-implementation of Biosustain Analytics Examples

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/SmartPeak2#81]
### Description
Port of examples from .py to cpp

### Objectives
**__main__**
- [x] example_LCMS_MRM_Unknowns
- [x] example_LCMS_MRM_Standards
- [x] example_LCMS_MRM_Validation
**test_main**
- [x] LC-MS examples
- [x] GC-MS examples
- [x] HPLC examples

### Validation
- [ ] Passing tests for the examples
