### ISSUE TITLE
Improved Filename and Sample name semantics

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/SmartPeak2#88]
### Description
In order to limit the amount of metaData required for users manually enter, we will need to change the way filenames and sample names are handled by smartPeak.  

### Objectives
- [x] Improved filename handling (issue #75 )
- [x] internal unique sample name semantics (issue #82 )

### Validation
- [x] updating examples demonstrating the integration of the changes
