### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/SmartPeak2#9]
### Objectives
- [ ] Continuous integration using Jenkins and Dart
- [x] Unit testing using Boost.Test library
- [ ] Continuous documentation building using Doxygen
